name: Wake Up Render Service

on:
  schedule:
    # 10:00 MSK = 07:00 UTC
    - cron: '0 7 * * *'
    # 22:00 MSK = 19:00 UTC
    - cron: '0 19 * * *'
  workflow_dispatch:

jobs:
  wake-up:
    runs-on: ubuntu-latest
    steps:
      - name: Send wake-up request
        run: |
          curl -X GET ${{ secrets.RENDER_SERVICE_URL }}/health
          sleep 5
          curl -X POST ${{ secrets.RENDER_SERVICE_URL }}/trigger_repost
